### ISSUE TITLE
feat: ファイルロギング

### ISSUE THREAD

**Issue by msato-ok** [minr-dev/desktop#118]
console.log で実装されているのでログの回収ができない。
ログファイルに保存されるようにする。

- ロギングの設計方針を作成する
- ロガーのライブラリを選定して、既存の console.log を置き替える

**Comment by yanagi-altus5** [comment]
(サブタスク)

- [ ] 現状のconsole.logの洗い出し
- [ ] ロギングの設計方針の作成
- [ ] ロガーの選定
- [ ] ロガーの設定を作成
- [ ] console.logを修正

**Comment by msato-ok** [comment]
- sprint-2: 消費 1.5日
- 合計 4.5人日で終わりそう

**Comment by msato-ok** [comment]
## 進捗メモ

- sprint-3での消費工数: 10人日
- これまでの消費トータル工数: 11.5人日
- タスク完了までの残工数(見込み): 3人日
- タスク全体工数(見込み): 14.5人日
- 進捗%: 79%

**Comment by msato-ok** [comment]
## 進捗メモ

- sprint-4での消費工数: 7.95人日
- これまでの消費トータル工数: 27.4人日
- タスク完了までの残工数(見込み): 2人日
- タスク全体工数(見込み): 29.4人日
- 進捗%: 93%

**Comment by msato-ok** [comment]
## 進捗メモ

- sprint-5での消費工数: 4.5人日
- これまでの消費トータル工数: 27.35人日
- タスク完了までの残工数(見込み): 0.5人日
- タスク全体工数(見込み): 27.85人日
- 進捗%: 98%
