### ISSUE TITLE
feat: OAuth認証を PKCE にする

### ISSUE THREAD

**Issue by msato-ok** [minr-dev/desktop#170]
現状、サーバーサイドに実装している OAuth 認証をクライアントに移して、スタンドアロンで外部サービスのAPIが使えるようにする。

サーバーサイドにある処理であれば、クレデンシャル情報をコードとして保持することができるが（リポジトリにコミットはしないが）、アプリを配布してスタンドアロンで動かすときに、現状のサーバーサイドの OAuth 処理を単純に移植すると、どうしても、アプリのバイナリの中にクレデンシャル情報が入ってしまう。
それでは脆弱なので、クレデンシャル情報を必要としない OAuth PKCE 方式に変更する。

### ライブラリについて
OAuthの認証用ライブラリとして、openid-clientを利用する。
旧バージョンである5.7.0を使う。新バージョンがESModuleであり、Electronで使うためには別途対応が必要なため。→ #178
このライブラリはOAuth 2.0の拡張仕様であるOpenID Connectに準拠している。
PKCE方式やデバイスフローにも対応している。

### Googleの認証方式について
PKCE方式で認証を行う。
Google側の仕様でなぜか`client_secret`が基本的に必須になってしまっているので、回避策として以下が必要。
GCP側のOAuthクライアントID作成時の設定で、プロジェクトをUWP(ユニバーサルWindowsプラットフォーム)にする。

### GitHubの認証方式について
GitHub側でPKCE方式の認証が実装されていないため、代替としてデバイスフロー方式で認証を行う。
GitHubのOAuth Appsの設定で「Enable Device Flow」にチェックを付ける必要がある。

GitHubではトークンリクエストのエラーのほとんどが200で返ってきて、RFCの規約に準拠していないため、openid-clientでは対応できない。
そのため、この部分のエラー処理は独自に実装する。

### アプリケーション内で管理する認証パラメータ
- クライアントID(環境変数から取得、ビルドプロセスで環境変数にセット)
- リダイレクトURI(環境変数から取得、ビルドプロセスで環境変数にセット、Googleのみ)
- アクセストークン(DBに保存)
- リフレッシュトークン(DBに保存、Googleのみ)

### デバイスフローのUIについて
ユーザーは以下の流れで認証を行う。
1. 設定>アカウントのタブから、GitHubの「認証する」ボタンを押下する。
2. 同ウィンドウにユーザーコードの表示と「コードを入力する」ボタンが表示される。
3. 「コードを入力する」ボタンを押下することで、別ウィンドウにGitHubのユーザーコード入力画面が表示される。
4. GitHubの画面に従ってユーザーコードを入力し、認証を行う。
5. 本体ウィンドウの方でユーザーコードの表示がなくなり、GitHubの「認証する」ボタンの部分が「認証解除」ボタンになっている。

**Comment by Hirotaka-Hanai** [comment]
サブタスク
- [ ] PKCE方式に関する調査
- [ ] 既存のGoogle認証フローをdesktopに移動する
- [ ] Google認証フローをPKCE方式に変更する
- [ ] 既存のGithub認証フローをdesktopに移動する
- [ ] Github認証フローをPKCE方式に変更する

**Comment by msato-ok** [comment]
## 進捗メモ

- sprint-4での消費工数: 2.6人日
- これまでの消費トータル工数: 5.2人日
- タスク完了までの残工数(見込み): 7人日
- タスク全体工数(見込み): 12.2人日
- 進捗%: 43%

**Comment by msato-ok** [comment]
## 進捗メモ

- sprint-5での消費工数: 5.5人日
- これまでの消費トータル工数: 10.15人日
- タスク完了までの残工数(見込み): 5人日
- タスク全体工数(見込み): 15.15人日
- 進捗%: 67%

**Comment by Hirotaka-Hanai** [comment]
# GoogleのPKCE認証について
Googleの認証はPKCE方式の認証フローに必要な`code_varifier`と`code_challendge`は実装されている。
一方で、`client_secret`が基本的に必須な仕様となっているため、セキュリティ的にクライアントアプリケーション側に認証を実装のが難しい。
https://stackoverflow.com/questions/60724690/using-google-oidc-with-code-flow-and-pkce
これを回避する方法として、GCP側のOAuthクライアントID作成時の設定で、プロジェクトをUWP(ユニバーサルWindowsプラットフォーム)にする手段がある。
https://stackoverflow.com/questions/76528208/google-oauth-2-0-authorization-code-with-pkce-requires-a-client-secret
こうすれば、認証時に`client_secret`を要求されなくなる。

**Comment by Hirotaka-Hanai** [comment]
## GitHubのPKCE認証について
GitHubは、PKCE方式の認証フローに必要な`code_varifier`と`code_challenge`を**実装していない**。
https://github.com/github/docs/blob/ffe54e43b4a88aaa43118445e5c24e58c93b440e/content/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps.md
そのため、PKCE方式による実装は現時点では不可能である。

GitHubでクライアントアプリケーションから安全に認証を行える手段は「デバイスフロー(RFC 8628)」しかないため、今回はこれを実装していくことにする。
https://docs.github.com/ja/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow

**Comment by Hirotaka-Hanai** [comment]
## 認証のパラメータをアプリケーション側に置くかどうか
### アプリケーション側に置くもの
- クライアントID(環境変数から取得)
- リダイレクトURI(環境変数から取得)
- アクセストークン(DBに保存)
- リフレッシュトークン(DBに保存)

### アプリケーション側に置いてはいけないもの
- クライアントシークレット

**Comment by Hirotaka-Hanai** [comment]
OAuthの認証用ライブラリとして、`openid-connect`を利用する。
最新版は6.0.0だが、ElectronでESモジュールを扱うのが簡単ではないため、ひとまずCommon JSで実装されている5.7.0を使う。

**Comment by Hirotaka-Hanai** [comment]
## GItHubでデバイスフローの認証を実装するときの注意点
ユーザーが認証を行うまで、アプリケーションは裏でアクセストークンのリクエストを送り続けることになるが、ここの処理は注意が必要。
ユーザーが認証を行う前にトークンリクエストを送った場合は、`authorization_pending`というエラーコードを返すことがデバイスフローの仕様で決まっている。
GitHubもこれに従っているが、エラーコードを返す時のHTTPステータスコードが200になっているので、`openid-client`の実装ではこれをエラーと認知できず、エラーレスポンスをトークンのレスポンスとして返してしまう。
そのため、`authorization_pending`が返ってきたときに再びリクエストを送る処理は独自に実装する必要がある。

**Comment by Hirotaka-Hanai** [comment]
@msato-ok 
デバイスフロー方式の認証画面のUIについて相談です。
認証のために、以下が必要になっています。
- ユーザーにコードを表示する
- ユーザーがコードを入力する画面を表示する
- コード入力画面への遷移ボタン

どのように表示するかについて、いくつか案を考えています。
1. 本体と別ウィンドウで、コードの表示とコード入力画面への遷移を行うボタンの配置を行い、ボタンを押すことで同じウィンドウでコード入力画面を表示する(コードの表示は消える)

| 表示内容 | 本体のウィンドウ | 別ウィンドウ1 | 別ウィンドウ2 |
| ---- | ---- | ---- | ---- |
| ユーザーが入力するコード | - | ○ | - |
| コード入力画面に遷移するボタン | - | ○ | - |
| コード入力画面 | - | ○ | - |
2. 1.でコード入力画面をさらに別ウィンドウにする

| 表示内容 | 本体のウィンドウ | 別ウィンドウ1 | 別ウィンドウ2 |
| ---- | ---- | ---- | ---- |
| ユーザーが入力するコード | - | ○ | - |
| コード入力画面に遷移するボタン | - | ○ | - |
| コード入力画面 | - | - | ○ |
3. 本体の画面でコードの表示とコード入力画面への遷移を行うボタンの配置を行い、ボタンを押すことで別ウィンドウでコード入力画面を表示する

| 表示内容 | 本体のウィンドウ | 別ウィンドウ1 | 別ウィンドウ2 |
| ---- | ---- | ---- | ---- |
| ユーザーが入力するコード | ○ | - | - |
| コード入力画面に遷移するボタン | ○ | - | - |
| コード入力画面 | - | ○ | - |

どのようにするのがよいでしょうか？

**Comment by msato-ok** [comment]
@Hirotaka-Hanai 

> * ユーザーにコードを表示する
> * ユーザーがコードを入力する画面を表示する
> * コード入力画面への遷移ボタン

コードとは何を指してますか？

**Comment by Hirotaka-Hanai** [comment]
打ち合わせ内容の記載

## デバイスフローの流れについて
1. アプリケーションがGitHubにリクエストを送り、以下を受け取る
  - `device_code`: アクセストークン取得リクエストの際に、デバイスの検証をするために用いる
  - `user_code`: ユーザーがブラウザに入力するコード
  - `verification_uri`: ユーザーが`user_code`を入力するページのURI
2. アプリケーションはユーザーに`user_code`と`verification_uri`を表示し、ユーザーはブラウザで`user_code`を入力する。(今回相談していた部分)
3. アプリケーションはユーザーが`user_code`を入力するまでの間、`device_code`を用いてトークンリクエストを送り続ける。

## 意見
- 一般的にはこのような検証はメールでユーザーコードとリンクを送る形式が多いが、その方式は可能か？
  - 送信先メールアドレスを知る術がないのでできない
- ユーザーコードは入力画面で入力する際にも見えていた方がよい
  - ユーザーコードを表示するウィンドウとユーザーコードを入力するウィンドウは別にした方がよい
- ユーザーコードの表示はアプリケーション本体側に実装する方が楽
- ユーザーに、ユーザーコードが表示されていることを認知してもらう必要がある

## 決定
ユーザーコードの表示はアプリケーション本体のウィンドウに表示する。
「認証する」ボタンを押した直後には、ユーザーコードの表示と「ユーザーコード入力画面を表示するボタン」の表示を行うだけにとどめ、いきなりユーザーコード入力画面のウィンドウを出すことはしない。
こうすることで、ユーザーがユーザーコードを見落とすことがなくなる。
