### ISSUE TITLE
feat: タスクから予定を自動作成する

### ISSUE THREAD

**Issue by msato-ok** [minr-dev/desktop#172]
朝一で今日の予定を作成する、あるいは、前日の終了時に翌日分の予定を作成することを想定し、
予定の自動生成を行う機能を追加する。

- 登録されているタスクのステータスが未完了のものを優先順で並べ替えて、優先度の高いものから、予定として作成する。
    - タスクにステータスの属性があるか確認し、ない場合は追加する
- 仕掛中のタスクは、進行状況に合わせて、時間の割り当てができるようにする必要がある
    - タスクに見積が必要
    - 進捗を測るために、タスクの実績を集計して、進捗の自動計算ができるようにする必要あり
    - 実績合計が見積を超えた場合の予定自動作成のルールを策定し実装する
        - 予定作成のトリガーの時点で、見積を実績が超えている場合は、ダイアログを表示して、追加する見積が入力できるようにする
- 全体設定
    - 一日の稼働時間（例 8時間）の設定
    - 就業開始時間の設定
    - 昼休み等の時間の設定（N個）
- 予定の自動登録方式
    - 一日分の予定なので、就業開始時間から終了時間までの空いてる予定に、上からタスクを詰め込んでいく

## タスクに追加する項目
- 予定工数
- 優先度(高、中、低)
- 期限日
- ~~進捗~~
  - 予定の自動登録のタイミングで都度計算する
- ステータス(未完了、完了)

## 進捗の計算方法
未完了のタスクを計算対象とする。予定の自動登録の直前に都度計算を行う。
**今回の実装では、登録された予定の合計時間で計算する。**
→実績だと、既に登録された今後の予定が計算に反映されないため
この計算がベストな方法とは言えないため、将来的に仕様が変わる可能性がある。

## 予定に組み込む順番
優先度の高いものから組み込む。同じ優先度の時は、期限日の早い方から。期限日がないものは同じ優先度内で最後に組み込まれる。

**Comment by msato-ok** [comment]
## サブタスク

- タスク登録の改修（見積と優先順位）
- 現在の進捗を計算する処理
- 予定を自動登録する処理

**Comment by Hirotaka-Hanai** [comment]
## タスクの優先順位について
プランニングの時点では1.の案を想定していましたが、使いづらい気がしたので別の案を提案します。
1. タスク内で優先順位を数値で設定する項目を追加する。
    - 「進行中のタスクの次に進める」のように相対的な基準で決めると、優先順位の数値が無限に大きくなってしまう。
    - 優先順位を振り直すことで解決できるが、結構な手間になる。
    - 優先順位自動振り直し機能みたいなのがあれば問題の解決になるかもしれない。
2. スプリント内で優先順位を決める(GitHubのスプリント的なイメージ)
    - スプリントの終わりで優先順位がリセットされるので上記の問題は発生しない。
    - 案の善し悪し以前に、工数の問題で見送るべきだとは思っている。
3. 優先順位の設定は「高」「中」「低」くらいにとどめ、優先順位の他に期限日の設定を作る。
    - 優先順位の高い方から予定に組み込み、同じ優先順位のタスクは期限日の早い方から組み込む。
    - 期限日が決まっていないタスクは同じ優先順位内で一番最後に組み込まれる。
    - 実装難易度的にちょうどいい落としどころかなと考えている。

@msato-ok 
いかがでしょうか？

**Comment by msato-ok** [comment]
@Hirotaka-Hanai 
3 がよさそうですね。
