### ISSUE TITLE
fix: Releaseがmac用のバイナリだけになっている

### ISSUE THREAD

**Issue by msato-ok** [minr-dev/desktop#177]
Windows版と、可能であれば、Linux 版も作成したい。

https://github.com/minr-dev/desktop/releases

step で OS 毎にビルドするのではなく、以下の workflow のように、matrix でビルドするように修正する。

https://github.com/terapyon/st-matrix-chart/blob/main/.github/workflows/build.yml

**Comment by Hirotaka-Hanai** [comment]
Build Electron AppとCreate GitHub Release and Upload Buildでリリース処理が重複してしまっているように見える。
そのせいでCreate GitHub Release and Upload Buildで重複した名前のファイルをリリースに上げようとしてエラーになっていそう。

**Comment by Hirotaka-Hanai** [comment]
macOSに配布して利用してもらうためにはコード署名と公証が必要
https://qiita.com/sprout2000/items/0fa5db89c43155f4f0c8
